package com.bits.api_bp.food_del_sys_g12.entities;

import jakarta.persistence.*;
import lombok.Data;

@Data
@Entity
@Table(name = "menu")
public class MenuEntity {

    @Id
    @Column(name = "id", nullable = false)
    private String id; // Unique identifier for each menu item

    @Column(name = "restaurant_id", nullable = false)
    private String restaurantId; // ID of the restaurant to which this menu item belongs

    @Column(name = "name", nullable = false)
    private String name; // Name of the menu item

    @Column(name = "description")
    private String description; // Description of the menu item

    @Column(name = "price", nullable = false)
    private Double price; // Price of the menu item

    @Column(name = "availability", nullable = false)
    private Boolean availability; // Indicates whether the item is available

    // Constructors, getters, and setters can be generated by Lombok with the @Data annotation
}
